"""
Builds web/public/africa-map.svg from Natural Earth 1:110m country outlines.

Natural Earth is public domain. Every African country is emitted as a filled
subpath of ONE path, in one colour, with nothing drawn between countries, so
the result is the continent's silhouette with no national borders. The note in
src/components/brand/AfricaMap.tsx explains why.

The projection is plain equirectangular. Africa straddles the equator, so the
distortion is negligible for a decorative map. It MUST stay in step with
project() in AfricaMap.tsx:

    x = (lon + 18) * 10,  y = (38 - lat) * 10,  viewBox 0 0 700 730

Usage:
    python web/scripts/build-africa-map.py [ne_110m_admin_0_countries.geojson]

Without a path the source file is downloaded.
"""

import json
import os
import sys
import urllib.request

SOURCE = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
    "master/geojson/ne_110m_admin_0_countries.geojson"
)
WEST, NORTH, SCALE = -18.0, 38.0, 10.0
WIDTH, HEIGHT = 700, 730
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "public", "africa-map.svg")


def load(path):
    if path:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    with urllib.request.urlopen(SOURCE) as response:
        return json.load(response)


def ring_to_path(ring):
    """One closed subpath in relative coordinates, rounded to whole units.

    A unit is a tenth of a degree, roughly 11 km. That is far finer than the
    map is ever drawn, and whole numbers in relative form keep the file small.
    """
    points, last = [], None
    for lon, lat in ring:
        point = (round((lon - WEST) * SCALE), round((NORTH - lat) * SCALE))
        if point != last:
            points.append(point)
            last = point
    if len(points) < 3:
        return ""

    x0, y0 = points[0]
    steps, px, py = [], x0, y0
    for x, y in points[1:]:
        steps.append(f"{x - px} {y - py}")
        px, py = x, y
    return f"M{x0} {y0}l" + " ".join(steps) + "z"


def main():
    data = load(sys.argv[1] if len(sys.argv) > 1 else None)
    parts = []
    for feature in data["features"]:
        if feature["properties"].get("CONTINENT") != "Africa":
            continue
        geometry = feature["geometry"]
        polygons = (
            geometry["coordinates"] if geometry["type"] == "MultiPolygon" else [geometry["coordinates"]]
        )
        for polygon in polygons:
            # Exterior rings only. An interior ring is a neighbour (Lesotho
            # inside South Africa) that its own feature fills anyway.
            subpath = ring_to_path(polygon[0])
            if subpath:
                parts.append(subpath)

    # The stroke is the fill colour, not a border. It closes the hairline
    # anti-aliasing seams where two countries meet, which would otherwise show
    # through the CSS mask as faint internal lines -- borders by accident.
    svg = (
        "<!-- Africa, Natural Earth 1:110m (public domain). "
        "Generated by web/scripts/build-africa-map.py -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}">'
        f'<path fill="#000" stroke="#000" stroke-width="2" stroke-linejoin="round" d="{"".join(parts)}"/>'
        "</svg>\n"
    )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(svg)
    print(f"wrote {os.path.normpath(OUT)}: {len(parts)} shapes, {len(svg) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
