package com.example.domain

import com.example.data.model.AppLanguage
import com.example.data.model.ProductCondition

object LocalizationManager {

    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_name" to "East-Market",
            "app_tagline" to "East Africa Online Marketplace",
            "home" to "Home",
            "categories" to "Categories",
            "sell" to "Sell",
            "messages" to "Messages",
            "profile" to "Profile",
            "search_placeholder" to "Search cars, phones, electronics, houses...",
            "all_categories" to "All Categories",
            "featured_listings" to "Featured Listings",
            "nearby_listings" to "Nearby Listings",
            "recent_listings" to "Recent Listings",
            "photo_listings" to "Photo listings",
            "photo_listings_hint" to "Everything sellers photographed",
            "video_listings" to "Video listings",
            "video_listings_hint" to "Watch full screen, one at a time",
            "no_videos" to "No videos yet",
            "buy_now" to "Buy",
            "back" to "Back",
            "popular_listings" to "Popular Deals",
            "sell_something" to "Sell Something",
            "post_listing" to "Post New Listing",
            "title" to "Title",
            "price" to "Price",
            "currency" to "Currency",
            "category" to "Category",
            "condition" to "Condition",
            "condition_new" to "New",
            "condition_like_new" to "Like New",
            "condition_refurbished" to "Refurbished",
            "condition_used" to "Used",
            "country" to "Country",
            "city" to "City",
            "description" to "Description",
            "video" to "Video",
            "watch_video" to "Watch the video",
            "phone" to "Phone Number",
            "whatsapp" to "WhatsApp Number",
            "negotiable" to "Price is negotiable",
            "delivery_available" to "Delivery available",
            "submit_listing" to "Publish Listing",
            "call" to "Call",
            "chat" to "Chat",
            "share" to "Share",
            "favorite" to "Favorite",
            "favorites" to "Favorites",
            // The contact button on a listing: "WhatsApp Number" wraps and clips there.
            "whatsapp_short" to "WhatsApp",
            "report" to "Report",
            "verified_seller" to "Verified Seller",
            "business_store" to "Business Store",
            "seller_info" to "Seller Information",
            "seller_listings" to "Seller's Other Products",
            "reviews" to "Reviews",
            "about" to "About",
            "rating" to "Rating",
            "joined" to "Joined",
            "language" to "Language",
            "display_currency" to "Display Currency",
            "data_saver" to "Low-Bandwidth Mode",
            "data_saver_desc" to "Compress images and reduce network usage",
            "safety_tips" to "Safety & Community Guidelines",
            "safety_tip_1" to "Meet in a safe public location for transactions",
            "safety_tip_2" to "Verify the product thoroughly before making payment",
            "terms" to "Terms of Service",
            "privacy" to "Privacy Policy",
            "filter" to "Filters",
            "sort_by" to "Sort By",
            "apply_filters" to "Apply Filters",
            "reset_filters" to "Reset",
            "no_products_found" to "No products found matching your search.",
            "type_message" to "Type a message...",
            "send" to "Send",
            "online" to "Online",
            "item_sold" to "Mark as Sold",
            "select_country" to "Select Your Country",
            "select_language" to "Select Language",
            "welcome" to "Welcome to East-Market",
            "welcome_subtitle" to "Buy, sell, and connect across East Africa with ease."
        ),
        AppLanguage.SOMALI to mapOf(
            "app_name" to "East-Market",
            "app_tagline" to "Suuqa Bariga Afrika ee Internetka",
            "home" to "Bogga Hore",
            "categories" to "Qaybaha",
            "sell" to "Iibi",
            "messages" to "Fariimaha",
            "profile" to "Koontada",
            "search_placeholder" to "Raadi baabuur, taleefan, guri, dhar...",
            "all_categories" to "Dhammaan Qaybaha",
            "featured_listings" to "Alaabaha La Soo Xulay",
            "nearby_listings" to "Alaabaha Kuugu Dhow",
            "recent_listings" to "Kuwii Ugu Dambeeyay",
            "photo_listings" to "Alaab sawiro leh",
            "photo_listings_hint" to "Wax kasta oo la sawiray",
            "video_listings" to "Alaab fiidiyow leh",
            "video_listings_hint" to "Shaashadda oo dhan, mid mid",
            "no_videos" to "Weli fiidiyow ma jiro",
            "buy_now" to "Iibso",
            "back" to "Dib u noqo",
            "popular_listings" to "Alaabaha Ugu Caansan",
            "sell_something" to "Alaab Iibi",
            "post_listing" to "Gali Alaab Cusub",
            "title" to "Magaca Alaabta",
            "price" to "Qiimaha",
            "currency" to "Lacagta",
            "category" to "Qaybta",
            "condition" to "Xaaladda",
            "condition_new" to "Cusub",
            "condition_like_new" to "Sida Cusub",
            "condition_refurbished" to "La Hagaajiyay",
            "condition_used" to "La Isticmaalay",
            "country" to "Dalka",
            "city" to "Magaalada",
            "description" to "Faahfaahinta",
            "video" to "Fiidiyow",
            "watch_video" to "Fiidiyowga daawo",
            "phone" to "Lambarka Taleefanka",
            "whatsapp" to "WhatsApp",
            "negotiable" to "Qiimaha waa la gorgortami karaa",
            "delivery_available" to "Gaarsiin waa la heli karaa",
            "submit_listing" to "Daabac Alaabta",
            "call" to "Wac",
            "chat" to "Wada hadal",
            "share" to "La wadaag",
            "favorite" to "Kaydi",
            "favorites" to "Kuwa la kaydiyay",
            "whatsapp_short" to "WhatsApp",
            "report" to "Dacwee",
            "verified_seller" to "Iibiye La Hubiyay",
            "business_store" to "Dukaan Ganacsi",
            "seller_info" to "Xogta Iibiyaha",
            "seller_listings" to "Alaabaha kale ee Iibiyaha",
            "reviews" to "Faallooyinka",
            "about" to "Ku saabsan",
            "rating" to "Qiimaynta",
            "joined" to "Kusoo biiray",
            "language" to "Luuqadda",
            "display_currency" to "Lacagta Bandhigga",
            "data_saver" to "Kaydinta Xogta (Data Saver)",
            "data_saver_desc" to "Yaree isticmaalka internetka iyo sawirrada",
            "safety_tips" to "Talooyinka Badbaadada",
            "safety_tip_1" to "Kula kulan goob ammaan ah oo dadweyne",
            "safety_tip_2" to "Hubi alaabta ka hor inta aadan lacag bixin",
            "terms" to "Shuruudaha Isticmaalka",
            "privacy" to "Xeerka Qarsoodiga",
            "filter" to "Kala Shaandhee",
            "sort_by" to "U kala saar",
            "apply_filters" to "Dhaqan gali",
            "reset_filters" to "Dib u celi",
            "no_products_found" to "Lama helin alaab la xiriirta raadintaada.",
            "type_message" to "Qor fariin...",
            "send" to "Dir",
            "online" to "Khadka ku jira",
            "item_sold" to "La Iibiyay",
            "select_country" to "Dooro Dalkaaga",
            "select_language" to "Dooro Luuqadda",
            "welcome" to "Kusoo dhawoow East-Market",
            "welcome_subtitle" to "Ku iibso oo ku iibi si fudud Bariga Afrika oo dhan."
        ),
        AppLanguage.AMHARIC to mapOf(
            "app_name" to "East-Market",
            "app_tagline" to "የምስራቅ አፍሪካ የመስመር ላይ ገበያ",
            "home" to "መነሻ",
            "categories" to "ምድቦች",
            "sell" to "ይሽጡ",
            "messages" to "መልእክቶች",
            "profile" to "መገለጫ",
            "search_placeholder" to "መኪና፣ ስልክ፣ ኮምፒውተር፣ ቤት ይፈልጉ...",
            "all_categories" to "ሁሉም ምድቦች",
            "featured_listings" to "ተለይተው የቀረቡ",
            "nearby_listings" to "በአቅራቢያዎ ያሉ",
            "recent_listings" to "አዳዲስ እቃዎች",
            "photo_listings" to "የፎቶ ዝርዝሮች",
            "photo_listings_hint" to "ሻጮች ፎቶ ያነሱት ሁሉ",
            "video_listings" to "የቪዲዮ ዝርዝሮች",
            "video_listings_hint" to "በሙሉ ስክሪን፣ አንድ በአንድ",
            "no_videos" to "እስካሁን ቪዲዮ የለም",
            "buy_now" to "ይግዙ",
            "back" to "ተመለስ",
            "popular_listings" to "ተወዳጅ እቃዎች",
            "sell_something" to "ምርት ይሽጡ",
            "post_listing" to "አዲስ ምርት ያስገቡ",
            "title" to "የምርት ስም",
            "price" to "ዋጋ",
            "currency" to "ገንዘብ",
            "category" to "ምድብ",
            "condition" to "ሁኔታ",
            "condition_new" to "አዲስ",
            "condition_like_new" to "እንደ አዲስ",
            "condition_refurbished" to "የታደሰ",
            "condition_used" to "ያገለገለ",
            "country" to "ሀገር",
            "city" to "ከተማ",
            "description" to "ዝርዝር መግለጫ",
            "video" to "ቪዲዮ",
            "watch_video" to "ቪዲዮውን ይመልከቱ",
            "phone" to "ስልክ ቁጥር",
            "whatsapp" to "WhatsApp",
            "negotiable" to "ዋጋው ይደራደራል",
            "delivery_available" to "ማድረስ አለ",
            "submit_listing" to "ምርቱን ይለጥፉ",
            "call" to "ይደውሉ",
            "chat" to "ይወያዩ",
            "share" to "አጋራ",
            "favorite" to "አስቀምጥ",
            "favorites" to "የተቀመጡ",
            "whatsapp_short" to "WhatsApp",
            "report" to "አመልክት",
            "verified_seller" to "የተረጋገጠ ሻጭ",
            "business_store" to "የንግድ ሱቅ",
            "seller_info" to "የሻጩ መረጃ",
            "seller_listings" to "ሌሎች የሻጩ ምርቶች",
            "reviews" to "ግምገማዎች",
            "about" to "ስለ",
            "rating" to "ደረጃ",
            "joined" to "የተመዘገበበት",
            "language" to "ቋንቋ",
            "display_currency" to "የሚታይበት ገንዘብ",
            "data_saver" to "ዳታ ቆጣቢ ሞድ",
            "data_saver_desc" to "የኢንተርኔት ፍጆታን እና የምስል ጥራትን መቀነስ",
            "safety_tips" to "የደህንነት መመሪያዎች",
            "safety_tip_1" to "ክፍያ ከመፈጸምዎ በፊት እቃውን በግል ያረጋግጡ",
            "safety_tip_2" to "ለግብይት ደህንነቱ በተጠበቀ የህዝብ ቦታ ይገናኙ",
            "terms" to "የአገልግሎት ውሎች",
            "privacy" to "የግላዊነት ፖሊሲ",
            "filter" to "ማጣሪያ",
            "sort_by" to "አደራጅ",
            "apply_filters" to "ተግብር",
            "reset_filters" to "አጽዳ",
            "no_products_found" to "ምንም የተገኘ ምርት የለም።",
            "type_message" to "መልእክት ይጻፉ...",
            "send" to "ላክ",
            "online" to "በመስመር ላይ",
            "item_sold" to "ተሽጧል",
            "select_country" to "ሀገርዎን ይምረጡ",
            "select_language" to "ቋንቋ ይምረጡ",
            "welcome" to "እንኳን ወደ East-Market በደህና መጡ",
            "welcome_subtitle" to "በምስራቅ አፍሪካ በቀላሉ ይግዙ፣ ይሽጡ እና ይገናኙ።"
        ),
        AppLanguage.SWAHILI to mapOf(
            "app_name" to "East-Market",
            "app_tagline" to "Soko la Mtandaoni la Afrika Mashariki",
            "home" to "Nyumbani",
            "categories" to "Kategoria",
            "sell" to "Uza",
            "messages" to "Ujumbe",
            "profile" to "Wasifu",
            "search_placeholder" to "Tafuta magari, simu, nguo, vifaa...",
            "all_categories" to "Kategoria Zote",
            "featured_listings" to "Bidhaa Maalum",
            "nearby_listings" to "Bidhaa Zilizo Karibu",
            "recent_listings" to "Zilizowekwa Karibuni",
            "photo_listings" to "Matangazo ya picha",
            "photo_listings_hint" to "Kila kitu kilichopigwa picha",
            "video_listings" to "Matangazo ya video",
            "video_listings_hint" to "Skrini nzima, moja baada ya jingine",
            "no_videos" to "Hakuna video bado",
            "buy_now" to "Nunua",
            "back" to "Rudi",
            "popular_listings" to "Zinazovuma",
            "sell_something" to "Uza Kitu",
            "post_listing" to "Weka Tangazo Jipya",
            "title" to "Jina la Bidhaa",
            "price" to "Bei",
            "currency" to "Sarafu",
            "category" to "Kategoria",
            "condition" to "Hali ya Bidhaa",
            "condition_new" to "Mpya",
            "condition_like_new" to "Kama Mpya",
            "condition_refurbished" to "Iliyoboreshwa",
            "condition_used" to "Iliyotumika",
            "country" to "Nchi",
            "city" to "Mji",
            "description" to "Maelezo",
            "video" to "Video",
            "watch_video" to "Tazama video",
            "phone" to "Nambari ya Simu",
            "whatsapp" to "WhatsApp",
            "negotiable" to "Bei inajadilika",
            "delivery_available" to "Usafirishaji unapatikana",
            "submit_listing" to "Chapisha Tangazo",
            "call" to "Piga Simu",
            "chat" to "Ongea",
            "share" to "Shiriki",
            "favorite" to "Hifadhi",
            "favorites" to "Vipendwa",
            "whatsapp_short" to "WhatsApp",
            "report" to "Ripoti",
            "verified_seller" to "Muuzaji Aliyethibitishwa",
            "business_store" to "Duka la Biashara",
            "seller_info" to "Taarifa za Muuzaji",
            "seller_listings" to "Bidhaa Zingine za Muuzaji",
            "reviews" to "Maoni",
            "about" to "Kuhusu",
            "rating" to "Ukadiriaji",
            "joined" to "Amejiunga",
            "language" to "Lugha",
            "display_currency" to "Sarafu ya Kuonyesha",
            "data_saver" to "Hali ya Kubana Data",
            "data_saver_desc" to "Punguza matumizi ya data na kasi ya mtandao",
            "safety_tips" to "Vidokezo vya Usalama",
            "safety_tip_1" to "Kutana katika sehemu ya umma iliyo salama",
            "safety_tip_2" to "Kagua bidhaa kabla ya kufanya malipo",
            "terms" to "Masharti ya Huduma",
            "privacy" to "Sera ya Faragha",
            "filter" to "Chuja",
            "sort_by" to "Panga Kwa",
            "apply_filters" to "Tekeleza",
            "reset_filters" to "Weka Upya",
            "no_products_found" to "Hakuna bidhaa zilizopatikana.",
            "type_message" to "Andika ujumbe...",
            "send" to "Tuma",
            "online" to "Mtandaoni",
            "item_sold" to "Imeuzwa",
            "select_country" to "Chagua Nchi Yako",
            "select_language" to "Chagua Lugha",
            "welcome" to "Karibu East-Market",
            "welcome_subtitle" to "Nunua na uuze kwa urahisi kote Afrika Mashariki."
        )
    )

    fun getString(key: String, language: AppLanguage): String {
        return translations[language]?.get(key)
            ?: translations[AppLanguage.ENGLISH]?.get(key)
            ?: key
    }

    fun getConditionString(condition: ProductCondition, language: AppLanguage): String {
        return when (condition) {
            ProductCondition.NEW -> getString("condition_new", language)
            ProductCondition.LIKE_NEW -> getString("condition_like_new", language)
            ProductCondition.REFURBISHED -> getString("condition_refurbished", language)
            ProductCondition.USED -> getString("condition_used", language)
        }
    }
}
